# Generated by Django 3.2 on 2022-10-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmwork',
            name='certificate',
            field=models.CharField(blank=True, max_length=512, verbose_name='certificate'),
        ),
        migrations.AddField(
            model_name='filmwork',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='movies/', verbose_name='file'),
        ),
        migrations.RunSQL(
            sql="""DROP INDEX film_work_person_idx;""",
            reverse_sql="""
                CREATE UNIQUE INDEX film_work_person_idx ON
                    content.person_film_work (film_work_id, person_id);
            """,
        ),
        migrations.RunSQL(
            sql="""
                 CREATE UNIQUE INDEX film_work_person_idx ON
                    content.person_film_work (film_work_id, person_id, role);
            """,
            reverse_sql='DROP INDEX film_work_person_idx;',
        ),

    ]
